### ISSUE TITLE
Can't delete Placid requests - Unknown error occurred

### ISSUE THREAD

**Issue by vegardsando** [alecritson/Placid#16]
After some problems with Placid objects returning NULL, my Facebook feed is still not working and returns NULL. 

So I thought I'd try to delete the stored Placid request from the control panel to create a new one. But I can't delete any stored requests. Even the Dribble Shots can't be deleted and I get a notification from the Craft GUI which says "Unkown error occurred".

I deleted the log files and made sure what's in it is fresh and relevant to this error. And what I get is the following:
```
`2015/10/28 12:12:29 [info] [application] $_POST=array (
  'id' => '1',
)

$_COOKIE=array (
  '6b523ef12eb2a8203cf8d9cbb8807780username' => 'b5725cffc284300cdfdea486429a71f2eb41f34cs:60:"3ba27ee3c067a611cdfdb7dab6d0c558b0bfc518czo3OiJtdXN0YXNqIjs=";',
  'CraftSessionId' => '1b590f53b07f03adfebc115b45775fee',
  '_ga' => 'GA1.2.209219278.1444302453',
  '6b523ef12eb2a8203cf8d9cbb8807780' => 'c818e94ceca2114bc078397388dc110dcff72931s:396:"d3a14965e888d214fdfba0545543f6ae52234aefYTo2OntpOjA7czo3OiJtdXN0YXNqIjtpOjE7czozMjoiSlhiQUNBbHliOG1IajBxfndvVE5oY0J1aUxsTl9uY3IiO2k6MjtzOjM2OiI2NGU0MGI1Mi1jOGY0LTQ2N2ItYjc5My01NmFlNGU3NTJiYWIiO2k6MztpOjA7aTo0O3M6MTIwOiJNb3ppbGxhLzUuMCAoTWFjaW50b3NoOyBJbnRlbCBNYWMgT1MgWCAxMF8xMF8zKSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvNDYuMC4yNDkwLjcxIFNhZmFyaS81MzcuMzYiO2k6NTthOjA6e319";',
)

$_SESSION=array (
  'temporary_credentials' => 'O:53:"League\\OAuth1\\Client\\Credentials\\TemporaryCredentials":2:{s:13:"' . "\0" . '*' . "\0" . 'identifier";s:27:"Sp3L0QAAAAAAiQs_AAABUK4Env8";s:9:"' . "\0" . '*' . "\0" . 'secret";s:32:"dVQEVMHyJ67ft3KV5igyACUwioRLPHSI";}',
  'token_credentials' => 'O:49:"League\\OAuth1\\Client\\Credentials\\TokenCredentials":2:{s:13:"' . "\0" . '*' . "\0" . 'identifier";s:50:"41125710-BAHyAvmvj46eD2AgGfKw9d1mCTWRZh2JmREJCuxkT";s:9:"' . "\0" . '*' . "\0" . 'secret";s:45:"nRPRghrJmxS2cwMwCydlCUVfzdbezqJV2wPBgMtb2fss5";}',
  '6b523ef12eb2a8203cf8d9cbb8807780__id' => '1',
  '6b523ef12eb2a8203cf8d9cbb8807780__name' => 'mustasj',
  '6b523ef12eb2a8203cf8d9cbb8807780__states' => 
  array (
  ),
  '6b523ef12eb2a8203cf8d9cbb8807780__timeout' => 4633278623,
  '6b523ef12eb2a8203cf8d9cbb8807780__auth_access' => 
  array (
    0 => 'uploadToAssetSource:2',
  ),
  '6b523ef12eb2a8203cf8d9cbb8807780__returnUrl' => 'placid',
  'facebook.referer' => 'http://bjugn.dev/admin/placid/oauth',
  'oauth2state' => '6f07bc062f79143ee35a8c6fcc6b6bb0',
)

$_SERVER=array (
  'HTTP_HOST' => 'bjugn.dev',
  'HTTP_CONNECTION' => 'keep-alive',
  'CONTENT_LENGTH' => '4',
  'HTTP_ACCEPT' => '*/*',
  'HTTP_ORIGIN' => 'http://bjugn.dev',
  'HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36',
  'CONTENT_TYPE' => 'application/x-www-form-urlencoded; charset=UTF-8',
  'HTTP_REFERER' => 'http://bjugn.dev/admin/placid',
  'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
  'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.8,nb;q=0.6',
  'HTTP_COOKIE' => '6b523ef12eb2a8203cf8d9cbb8807780username=b5725cffc284300cdfdea486429a71f2eb41f34cs%3A60%3A%223ba27ee3c067a611cdfdb7dab6d0c558b0bfc518czo3OiJtdXN0YXNqIjs%3D%22%3B; CraftSessionId=1b590f53b07f03adfebc115b45775fee; _ga=GA1.2.209219278.1444302453; 6b523ef12eb2a8203cf8d9cbb8807780=c818e94ceca2114bc078397388dc110dcff72931s%3A396%3A%22d3a14965e888d214fdfba0545543f6ae52234aefYTo2OntpOjA7czo3OiJtdXN0YXNqIjtpOjE7czozMjoiSlhiQUNBbHliOG1IajBxfndvVE5oY0J1aUxsTl9uY3IiO2k6MjtzOjM2OiI2NGU0MGI1Mi1jOGY0LTQ2N2ItYjc5My01NmFlNGU3NTJiYWIiO2k6MztpOjA7aTo0O3M6MTIwOiJNb3ppbGxhLzUuMCAoTWFjaW50b3NoOyBJbnRlbCBNYWMgT1MgWCAxMF8xMF8zKSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvNDYuMC4yNDkwLjcxIFNhZmFyaS81MzcuMzYiO2k6NTthOjA6e319%22%3B',
  'PATH' => '/usr/bin:/bin:/usr/sbin:/sbin',
  'SERVER_SIGNATURE' => '',
  'SERVER_SOFTWARE' => 'Apache',
  'SERVER_NAME' => 'bjugn.dev',
  'SERVER_ADDR' => '::1',
  'SERVER_PORT' => '80',
  'REMOTE_ADDR' => '::1',
  'DOCUMENT_ROOT' => '/Users/mustasj/Documents/git/bjugn.no/www',
  'SERVER_ADMIN' => 'you@example.com',
  'SCRIPT_FILENAME' => '/Users/mustasj/Documents/git/bjugn.no/www/index.php',
  'REMOTE_PORT' => '59764',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_METHOD' => 'POST',
  'QUERY_STRING' => '',
  'REQUEST_URI' => '/index.php/admin/actions/placid/requests/deleteRequest',
  'SCRIPT_NAME' => '/index.php',
  'PATH_INFO' => '/admin/actions/placid/requests/deleteRequest',
  'PATH_TRANSLATED' => 'redirect:/index.php/actions/placid/requests/deleteRequest',
  'PHP_SELF' => '/index.php/admin/actions/placid/requests/deleteRequest',
  'REQUEST_TIME_FLOAT' => 1446034349.15100002288818359375,
  'REQUEST_TIME' => 1446034349,
  'argv' => 
  array (
  ),
  'argc' => 0,
)
2015/10/28 12:12:29 [trace] [system.CModule] Loading "log" application component
in /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/web/WebApp.php (584)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/web/WebApp.php (124)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/bootstrap.php (189)
2015/10/28 12:12:29 [trace] [system.CModule] Loading "coreMessages" application component
in /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/web/WebApp.php (584)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/web/WebApp.php (127)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/bootstrap.php (189)
2015/10/28 12:12:29 [trace] [system.db.CDbConnection] Opening DB connection
in /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/behaviors/AppBehavior.php (824)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/web/WebApp.php (580)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/behaviors/AppBehavior.php (80)
2015/10/28 12:12:29 [trace] [system.db.CDbCommand] Querying SQL: SHOW TABLES LIKE 'craft_%'
in /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/db/schemas/MysqlSchema.php (295)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/db/DbConnection.php (90)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/behaviors/AppBehavior.php (98)
2015/10/28 12:12:29 [profile] [system.db.CDbCommand.query] begin:system.db.CDbCommand.query(SHOW TABLES LIKE 'craft_%')
2015/10/28 12:12:29 [profile] [system.db.CDbCommand.query] end:system.db.CDbCommand.query(SHOW TABLES LIKE 'craft_%')
2015/10/28 12:12:29 [trace] [system.db.CDbCommand] Querying SQL: SELECT *
FROM `craft_info` LIMIT 1
in /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/behaviors/AppBehavior.php (492)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/behaviors/AppBehavior.php (187)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/web/WebApp.php (719)
2015/10/28 12:12:29 [profile] [system.db.CDbCommand.query] begin:system.db.CDbCommand.query(SELECT *
FROM `craft_info` LIMIT 1)
2015/10/28 12:12:29 [profile] [system.db.CDbCommand.query] end:system.db.CDbCommand.query(SELECT *
FROM `craft_info` LIMIT 1)
2015/10/28 12:12:29 [trace] [system.CModule] Loading "userSession" application component
in /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/web/WebApp.php (584)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/web/WebApp.php (158)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/index.php (62)
2015/10/28 12:12:29 [trace] [system.CModule] Loading "security" application component
in /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/web/WebApp.php (584)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/web/CookieCollection.php (41)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/services/HttpRequestService.php (882)
2015/10/28 12:12:29 [trace] [system.CModule] Loading "statePersister" application component
in /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/web/WebApp.php (584)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/web/CookieCollection.php (41)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/services/HttpRequestService.php (882)
2015/10/28 12:12:29 [trace] [system.caching.Craft\FileCache] Serving "Yii.CStatePersister./Users/mustasj/Documents/git/bjugn.no/craft/storage/runtime/state/state.bin" from cache
in /Users/mustasj/Documents/git/bjugn.no/craft/app/services/CacheService.php (169)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/web/CookieCollection.php (41)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/services/HttpRequestService.php (882)
2015/10/28 12:12:29 [trace] [system.CModule] Loading "httpSession" application component
in /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/web/WebApp.php (584)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/web/WebApp.php (477)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/services/UserSessionService.php (92)
2015/10/28 12:12:29 [trace] [system.CModule] Loading "session" application component
in /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/web/WebApp.php (584)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/services/UserSessionService.php (1087)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/services/UserSessionService.php (376)
2015/10/28 12:12:29 [trace] [system.db.CDbCommand] Querying SQL: SELECT *
FROM `craft_users`
WHERE id=:id. Bound with :id='1'
in /Users/mustasj/Documents/git/bjugn.no/craft/app/services/UserSessionService.php (1535)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/services/UserSessionService.php (376)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/services/UserSessionService.php (841)
2015/10/28 12:12:29 [profile] [system.db.CDbCommand.query] begin:system.db.CDbCommand.query(SELECT *
FROM `craft_users`
WHERE id=:id. Bound with :id='1')
2015/10/28 12:12:29 [profile] [system.db.CDbCommand.query] end:system.db.CDbCommand.query(SELECT *
FROM `craft_users`
WHERE id=:id. Bound with :id='1')
2015/10/28 12:12:29 [trace] [system.CModule] Loading "securityManager" application component
in /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/web/WebApp.php (584)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/services/UserSessionService.php (1272)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/services/UserSessionService.php (92)
2015/10/28 12:12:29 [trace] [system.caching.Craft\FileCache] Serving "appPath" from cache
in /Users/mustasj/Documents/git/bjugn.no/craft/app/services/CacheService.php (169)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/web/WebApp.php (836)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/web/WebApp.php (203)
2015/10/28 12:12:29 [trace] [system.CModule] Loading "updates" application component
in /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/web/WebApp.php (584)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/web/WebApp.php (206)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/index.php (62)
2015/10/28 12:12:29 [trace] [system.CModule] Loading "plugins" application component
in /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/web/WebApp.php (584)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/web/WebApp.php (246)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/index.php (62)
2015/10/28 12:12:29 [trace] [system.db.CDbCommand] Querying SQL: SELECT `id`, `class`, `version`, `settings`, `installDate`
FROM `craft_plugins`
WHERE enabled=1
in /Users/mustasj/Documents/git/bjugn.no/craft/app/services/PluginsService.php (102)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/web/WebApp.php (246)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/index.php (62)
2015/10/28 12:12:29 [profile] [system.db.CDbCommand.query] begin:system.db.CDbCommand.query(SELECT `id`, `class`, `version`, `settings`, `installDate`
FROM `craft_plugins`
WHERE enabled=1)
2015/10/28 12:12:29 [profile] [system.db.CDbCommand.query] end:system.db.CDbCommand.query(SELECT `id`, `class`, `version`, `settings`, `installDate`
FROM `craft_plugins`
WHERE enabled=1)
2015/10/28 12:12:29 [trace] [system.CModule] Loading "messages" application component
in /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/web/WebApp.php (584)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/Craft.php (382)
in /Users/mustasj/Documents/git/bjugn.no/plugins/obsoleteredirect/ObsoleteRedirectPlugin.php (9)
2015/10/28 12:12:29 [trace] [system.CModule] Loading "i18n" application component
in /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/web/WebApp.php (584)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/behaviors/AppBehavior.php (737)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/behaviors/AppBehavior.php (570)
2015/10/28 12:12:29 [trace] [system.db.CDbCommand] Querying SQL: SELECT `locale`
FROM `craft_locales`
ORDER BY `sortOrder`
in /Users/mustasj/Documents/git/bjugn.no/craft/app/services/LocalizationService.php (126)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/services/LocalizationService.php (173)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/behaviors/AppBehavior.php (737)
2015/10/28 12:12:29 [profile] [system.db.CDbCommand.query] begin:system.db.CDbCommand.query(SELECT `locale`
FROM `craft_locales`
ORDER BY `sortOrder`)
2015/10/28 12:12:29 [profile] [system.db.CDbCommand.query] end:system.db.CDbCommand.query(SELECT `locale`
FROM `craft_locales`
ORDER BY `sortOrder`)
2015/10/28 12:12:29 [trace] [system.CModule] Loading "templates" application component
in /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/web/WebApp.php (584)
in /Users/mustasj/Documents/git/bjugn.no/plugins/guano/GuanoPlugin.php (40)
in /Users/mustasj/Documents/git/bjugn.no/plugins/guano/GuanoPlugin.php (11)
2015/10/28 12:12:29 [trace] [system.CModule] Loading "resources" application component
in /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/web/WebApp.php (584)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/helpers/UrlHelper.php (250)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/services/TemplatesService.php (429)
2015/10/28 12:12:29 [trace] [system.caching.Craft\FileCache] Serving "resourcePath:guano/css/guano.css" from cache
in /Users/mustasj/Documents/git/bjugn.no/craft/app/services/CacheService.php (169)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/services/ResourcesService.php (41)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/helpers/UrlHelper.php (254)
2015/10/28 12:12:29 [trace] [system.caching.Craft\FileCache] Serving "resourcePath:guano/js/guano.js" from cache
in /Users/mustasj/Documents/git/bjugn.no/craft/app/services/CacheService.php (169)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/services/ResourcesService.php (41)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/helpers/UrlHelper.php (254)
2015/10/28 12:12:29 [trace] [system.caching.Craft\FileCache] Serving "resourcePath:utilsme/css/utilsMe.css" from cache
in /Users/mustasj/Documents/git/bjugn.no/craft/app/services/CacheService.php (169)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/services/ResourcesService.php (41)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/helpers/UrlHelper.php (254)
2015/10/28 12:12:29 [trace] [system.caching.Craft\FileCache] Serving "resourcePath:utilsme/js/utilsMe.js" from cache
in /Users/mustasj/Documents/git/bjugn.no/craft/app/services/CacheService.php (169)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/services/ResourcesService.php (41)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/helpers/UrlHelper.php (254)
2015/10/28 12:12:29 [trace] [system.CModule] Loading "urlManager" application component
in /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/web/WebApp.php (584)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/controllers/BaseController.php (50)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/web/WebApp.php (784)
2015/10/28 12:12:29 [trace] [system.CModule] Loading "placid_requests" application component
in /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/web/WebApp.php (584)
in /Users/mustasj/Documents/git/bjugn.no/plugins/placid/controllers/Placid_RequestsController.php (99)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/web/WebApp.php (784)
2015/10/28 12:12:29 [trace] [system.db.CDbCommand] Querying SQL: SHOW FULL COLUMNS FROM `craft_placid_requests`
in /Users/mustasj/Documents/git/bjugn.no/craft/app/records/BaseRecord.php (49)
in /Users/mustasj/Documents/git/bjugn.no/plugins/placid/services/Placid_RequestsService.php (40)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/web/WebApp.php (584)
2015/10/28 12:12:29 [profile] [system.db.CDbCommand.query] begin:system.db.CDbCommand.query(SHOW FULL COLUMNS FROM `craft_placid_requests`)
2015/10/28 12:12:29 [profile] [system.db.CDbCommand.query] end:system.db.CDbCommand.query(SHOW FULL COLUMNS FROM `craft_placid_requests`)
2015/10/28 12:12:29 [trace] [system.db.CDbCommand] Querying SQL: SHOW CREATE TABLE `craft_placid_requests`
in /Users/mustasj/Documents/git/bjugn.no/craft/app/records/BaseRecord.php (49)
in /Users/mustasj/Documents/git/bjugn.no/plugins/placid/services/Placid_RequestsService.php (40)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/web/WebApp.php (584)
2015/10/28 12:12:29 [profile] [system.db.CDbCommand.query] begin:system.db.CDbCommand.query(SHOW CREATE TABLE `craft_placid_requests`)
2015/10/28 12:12:29 [profile] [system.db.CDbCommand.query] end:system.db.CDbCommand.query(SHOW CREATE TABLE `craft_placid_requests`)
2015/10/28 12:12:29 [trace] [system.db.ar.CActiveRecord] Craft\Placid_RequestsRecord.findByPk()
in /Users/mustasj/Documents/git/bjugn.no/plugins/placid/services/Placid_RequestsService.php (515)
in /Users/mustasj/Documents/git/bjugn.no/plugins/placid/services/Placid_RequestsService.php (277)
in /Users/mustasj/Documents/git/bjugn.no/plugins/placid/controllers/Placid_RequestsController.php (99)
2015/10/28 12:12:29 [trace] [system.db.CDbCommand] Querying SQL: SELECT * FROM `craft_placid_requests` `t` WHERE `t`.`id`=1 LIMIT 1
in /Users/mustasj/Documents/git/bjugn.no/plugins/placid/services/Placid_RequestsService.php (515)
in /Users/mustasj/Documents/git/bjugn.no/plugins/placid/services/Placid_RequestsService.php (277)
in /Users/mustasj/Documents/git/bjugn.no/plugins/placid/controllers/Placid_RequestsController.php (99)
2015/10/28 12:12:29 [profile] [system.db.CDbCommand.query] begin:system.db.CDbCommand.query(SELECT * FROM `craft_placid_requests` `t` WHERE `t`.`id`=1 LIMIT 1)
2015/10/28 12:12:29 [profile] [system.db.CDbCommand.query] end:system.db.CDbCommand.query(SELECT * FROM `craft_placid_requests` `t` WHERE `t`.`id`=1 LIMIT 1)
2015/10/28 12:12:29 [trace] [system.CModule] Loading "dashboard" application component
in /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/web/WebApp.php (584)
in /Users/mustasj/Documents/git/bjugn.no/plugins/placid/services/Placid_RequestsService.php (517)
in /Users/mustasj/Documents/git/bjugn.no/plugins/placid/services/Placid_RequestsService.php (277)
2015/10/28 12:12:29 [trace] [system.db.CDbCommand] Querying SQL: SHOW FULL COLUMNS FROM `craft_widgets`
in /Users/mustasj/Documents/git/bjugn.no/craft/app/services/DashboardService.php (332)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/services/DashboardService.php (332)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/services/DashboardService.php (62)
2015/10/28 12:12:29 [profile] [system.db.CDbCommand.query] begin:system.db.CDbCommand.query(SHOW FULL COLUMNS FROM `craft_widgets`)
2015/10/28 12:12:29 [profile] [system.db.CDbCommand.query] end:system.db.CDbCommand.query(SHOW FULL COLUMNS FROM `craft_widgets`)
2015/10/28 12:12:29 [trace] [system.db.CDbCommand] Querying SQL: SHOW CREATE TABLE `craft_widgets`
in /Users/mustasj/Documents/git/bjugn.no/craft/app/services/DashboardService.php (332)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/services/DashboardService.php (332)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/services/DashboardService.php (62)
2015/10/28 12:12:29 [profile] [system.db.CDbCommand.query] begin:system.db.CDbCommand.query(SHOW CREATE TABLE `craft_widgets`)
2015/10/28 12:12:29 [profile] [system.db.CDbCommand.query] end:system.db.CDbCommand.query(SHOW CREATE TABLE `craft_widgets`)
2015/10/28 12:12:29 [trace] [system.db.ar.CActiveRecord] Craft\WidgetRecord.findAllByAttributes()
in /Users/mustasj/Documents/git/bjugn.no/craft/app/services/DashboardService.php (334)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/services/DashboardService.php (62)
in /Users/mustasj/Documents/git/bjugn.no/plugins/placid/services/Placid_RequestsService.php (517)
2015/10/28 12:12:29 [trace] [system.db.CDbCommand] Querying SQL: SELECT * FROM `craft_widgets` `t` WHERE `t`.`userId`=:yp0 ORDER BY sortOrder. Bound with :yp0='1'
in /Users/mustasj/Documents/git/bjugn.no/craft/app/services/DashboardService.php (334)
in /Users/mustasj/Documents/git/bjugn.no/craft/app/services/DashboardService.php (62)
in /Users/mustasj/Documents/git/bjugn.no/plugins/placid/services/Placid_RequestsService.php (517)
2015/10/28 12:12:29 [profile] [system.db.CDbCommand.query] begin:system.db.CDbCommand.query(SELECT * FROM `craft_widgets` `t` WHERE `t`.`userId`=:yp0 ORDER BY sortOrder. Bound with :yp0='1')
2015/10/28 12:12:29 [profile] [system.db.CDbCommand.query] end:system.db.CDbCommand.query(SELECT * FROM `craft_widgets` `t` WHERE `t`.`userId`=:yp0 ORDER BY sortOrder. Bound with :yp0='1')
2015/10/28 12:12:29 [error] [php] array_key_exists() expects parameter 2 to be array, null given (/Users/mustasj/Documents/git/bjugn.no/plugins/placid/services/Placid_RequestsService.php:522)
Stack trace:
#0 /Users/mustasj/Documents/git/bjugn.no/plugins/placid/controllers/Placid_RequestsController.php(99): Craft\Placid_RequestsService->deleteRecordById()
#1 /Users/mustasj/Documents/git/bjugn.no/craft/app/framework/web/actions/CInlineAction.php(49): Craft\Placid_RequestsController->actionDeleteRequest()
#2 /Users/mustasj/Documents/git/bjugn.no/craft/app/framework/web/CController.php(308): CInlineAction->runWithParams()
#3 /Users/mustasj/Documents/git/bjugn.no/craft/app/framework/web/CController.php(286): Craft\Placid_RequestsController->runAction()
#4 /Users/mustasj/Documents/git/bjugn.no/craft/app/framework/web/CController.php(265): Craft\Placid_RequestsController->runActionWithFilters()
#5 /Users/mustasj/Documents/git/bjugn.no/craft/app/framework/web/CWebApplication.php(282): Craft\Placid_RequestsController->run()
#6 /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/web/WebApp.php(784): Craft\WebApp->runController()
#7 /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/web/WebApp.php(276): Craft\WebApp->_processActionRequest()
#8 /Users/mustasj/Documents/git/bjugn.no/craft/app/framework/base/CApplication.php(184): Craft\WebApp->processRequest()
#9 /Users/mustasj/Documents/git/bjugn.no/craft/app/index.php(62): Craft\WebApp->run()
#10 /Users/mustasj/Documents/git/bjugn.no/www/index.php(26): require_once()
REQUEST_URI=/index.php/admin/actions/placid/requests/deleteRequest
in /Users/mustasj/Documents/git/bjugn.no/plugins/placid/services/Placid_RequestsService.php (522)
in /Users/mustasj/Documents/git/bjugn.no/plugins/placid/services/Placid_RequestsService.php (277)
in /Users/mustasj/Documents/git/bjugn.no/plugins/placid/controllers/Placid_RequestsController.php (99)
2015/10/28 12:12:29 [trace] [system.CModule] Loading "errorHandler" application component
in /Users/mustasj/Documents/git/bjugn.no/craft/app/etc/web/WebApp.php (584)
in /Users/mustasj/Documents/git/bjugn.no/plugins/placid/services/Placid_RequestsService.php (522)
in /Users/mustasj/Documents/git/bjugn.no/plugins/placid/services/Placid_RequestsService.php (277)

******************************************************************************************************
 ```
I'm not sure if this is related to my initial problem with the Facebook feed returning NULL, but I can't get to the bottom of it unless I try to remove the request and create a new one

Edit: I tried to uninstall Placid alltogether and install it again. And the same thing happens when trying to delete the built inn Dribble Shots request

**Comment by alecritson** [comment]
Hey @vegardsando 

Looks like you found another bug (I should give you a gold star). Ive just pushed [`1.6.4`](https://github.com/alecritson/Placid/releases/tag/1.6.4) which should address the issue you are having, but let me know if it doesn't.

Thats strange you are still getting NULL , is there anything in the Placid log which could still indicate this?

**Comment by alecritson** [comment]
Hold tight there is a syntax error, was in twig mode...

**Comment by alecritson** [comment]
Github seems to have cached the release i'm trying to override so try downloading from [`master`](https://github.com/alecritson/Placid/archive/master.zip) to get the latest..

**Comment by vegardsando** [comment]
Ok, I've updated to the latest version of Placid now. And I can now delete stored requests :)
However, regarding the Facebook thing. After I'd deleted everything related to the Facebook request, I created the OAuth entry and try clicking "Connect to Facebook" and here I notice that the URL it tries to go to is `admin/placid/oauth#_=_` with the correct domain name first of course. 

Then there is this error thrown from the Craft control panel which says the following:

`Required option not passed: access_token Array ( [{"error":{"message":"Error_validating_client_secret_","type":"OAuthException","code":1,"fbtrace_id":"FClGJYj3k23"}}] => )`

**Comment by alecritson** [comment]
This is interesting, I can connect to facebook just fine. Are you sure your facebook client secret and key are correct in the OAuth settings?

**Comment by vegardsando** [comment]
Ooh, looks like I derped :) I had changed the token secret, but hadn't updated the OAuth info.
It's connected just fine now, and btw, the URL still contained `oauth#_=_` so that was no indication of any error. 

I'm gonna try to see if I can get anything else but NULL from the object now

**Comment by vegardsando** [comment]
And it's working! Halleluja!
Thank you for excellent support! :)
